### ISSUE TITLE
Crash reported by Posten

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-sitemap-xml#2]
Enonic version:6.10.1 
Operating system ::CentOS release 6.7 (Final)

Now when we try to read sitemap.xml of our web site after installing the app ,it gives below error. 
Caused by: org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.createElement(CoreDocumentImpl.java:665) ~[na:1.8.0_121] 
at com.enonic.xp.xml.DomBuilder.createElement(DomBuilder.java:33) ~[na:na] 
at com.enonic.xp.xml.DomBuilder.start(DomBuilder.java:39) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeMap(MapToXmlConverter.java:24) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeObject(MapToXmlConverter.java:38) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeMap(MapToXmlConverter.java:25) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeObject(MapToXmlConverter.java:38) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeList(MapToXmlConverter.java:51) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeObject(MapToXmlConverter.java:34) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeMap(MapToXmlConverter.java:25) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeObject(MapToXmlConverter.java:38) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeMap(MapToXmlConverter.java:25) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeObject(MapToXmlConverter.java:38) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeMap(MapToXmlConverter.java:25) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeObject(MapToXmlConverter.java:38) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeMap(MapToXmlConverter.java:25) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeObject(MapToXmlConverter.java:38) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeList(MapToXmlConverter.java:51) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeObject(MapToXmlConverter.java:34) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.serializeMap(MapToXmlConverter.java:25) ~[na:na] 
at com.enonic.xp.lib.xslt.MapToXmlConverter.toSource(MapToXmlConverter.java:16) ~[na:na] 
at com.enonic.xp.lib.xslt.XsltProcessor.setModel(XsltProcessor.java:59) ~[na:na] 
at jdk.nashorn.internal.scripts.Script$Recompilation$287$609AA$xslt.L:1#render(com.enonic.app.sitemapxml:/site/lib/xp/xslt.js:24)

**Comment by Bellfalasch** [comment]
Hard to debug, most likely because of missing settings. Solved in #6
